spring:
  application:
    name: ufo-sighting
  datasource:
    url: jdbc:postgresql://localhost:5432/ufo-sighting
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    show-sql: false
  liquibase:
    drop-first: false
    enabled: true